package Common;

public enum Command {
    LOGIN,USERNAME_UNIQUE,SIGNUP,LOGOUT,UPDATE_INFO,FORGOT_PASSWORD,SET_PASSWORD,ADD_POST,LIKE_POST,REPOST,DELETE_ACCOUNT,TIME_LINE,GET_PASSWORD,MY_POSTS,UPDATE_POST,VIEW_COMMENTS,ADD_COMMENT,GET_PROFILES,FOLLOW,UPDATE_PROFILE,GET_POST,GET_INFO,FOLLOWERS_LIST,FOLLOWINGS_LIST,UPDATE_PROF
}
